apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
  namespace: mateapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi